### PR TITLE
Remove upper bound on globalize version

### PR DESCRIPTION
**Pull request by courtenay**
as there is a version 5 now.

### CODE REVIEW

**Comment by parndt** [comment]
Does it work with version 5?

**Comment by courtenay** [comment]
Good question ;) (checks)

**Comment by simi** [comment]
CI will tell us.

**Comment by courtenay** [comment]
looks like an (unrelated) dependency issue with minitest and rails 4.2 (requires newer minitest version)

**Comment by courtenay** [comment]
(looking into it)

**Comment by simi** [comment]
@courtenay I'm trying this also https://github.com/globalize/globalize-versioning/pull/9.

**Comment by simi** [comment]
@courtenay thanks for taking this on the air! I fixe this in #9. `0.1.0` will be release in minute.

**Pull request closed without merging**
