### PR TITLE
Update for Rails 5

### PR DESCRIPTION
**Pull request by besi**
I am currently updating my application to Rails 5 and globalize-versioning is currently blocking this because it depends on `activerecord < 5`.

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    globalize-versioning was resolved to 0.2.0, which depends on
      globalize (< 6, >= 3.0.4) was resolved to 5.1.0.beta2, which depends on
        activerecord (< 5.2, >= 4.2)

    globalize-versioning was resolved to 0.2.0, which depends on
      activerecord (< 5, >= 3.2.0)

    rails (~> 5.1.3) was resolved to 5.1.3, which depends on
      activerecord (= 5.1.3)
```

### CODE REVIEW

**Comment by besi** [comment]
See https://stackoverflow.com/questions/45710933/replace-alias-method-chain-with-moduleprepend

**Comment by simi** [comment]
Hello @besi. Thanks for contribution. It will be great to test Rails 5 support also on Travis CI. I can help you with that, if you want. Feel free to ping me.

**Comment by besi** [comment]
@simi Hy Simi thank you very much for your offer. I am now again fumbling with this issue. Since I would like to add a history for my translations, which broke somewhere along the road:

history

I just updated the `.travis` config in 0d3c243.

Please let me know if I'm missing something.

**Comment by besi** [comment]
https://travis-ci.org/globalize/globalize-versioning/jobs/282274737#L566

The tests fail. This is also what I can reproduce locally. I haven't yet completely grasped how we get the `paper_trail` hooked up with the translations model. I am currently only a user of globalize, paper_trail and globalize-versioning so I think I do need some help with this.

**Comment by besi** [comment]
I asked for help at [Stackoverflow](https://stackoverflow.com/questions/46527871/dynamically-adding-paper-trail-to-translations-in-rails5)

**Comment by ikanyu** [comment]
Hi, is there any update on this PR? Would love to have compatibility with Rails 5 🙂

**Comment by vestimir** [comment]
Hey, what's the status of this one? How can we help to get this merged?

**Comment by parndt** [comment]
This was fixed by #21 - thank you so much though 🙇

**Comment by besi** [comment]
See https://github.com/globalize/globalize-versioning/pull/21

**Pull request closed without merging**
