### PR TITLE
Rails 7 upgrade

### PR DESCRIPTION
**Pull request by gentlemich**
See #25

### CODE REVIEW

**Comment by santib** [comment]
@parndt do you think it's possible to release a new version with this? 🙏

**Comment by parndt** [comment]
Sure - I take it that it's all working fine for you as well @santib, when you use this PR as your source ?

**Comment by santib** [comment]
@parndt My tests pass 😄 . I think Shopify devs have been pushing gems to stop setting an upper bound on their dependencies, to make upgrades smoother, or even allow people to use the rails main branch. I think I like that approach, WDYT?

**Comment by parndt** [comment]
Thanks @santib; the problem with that approach is that as soon as a new version of something like Rails comes out it will automatically be possible to start using it with this gem, which sounds great - nice and easy - but that comes with an implicit contract that this gem works with the new version of Rails which hasn't actually been tested to validate. 

This could be a non-event, or it could lead to all sorts of problems, including breaking the data in your database because something important has changed in ActiveRecord (common!). 

This is, I think, one reason why gem maintainers are hesitant to have open ended dependencies.

Another thing is that when creating a gem with `gem build` we see this sort of message from rubygems itself, warning against it:

```
$ gem build globalize-versioning.gemspec   
WARNING:  open-ended dependency on activerecord (>= 4.2.0) is not recommended
  if activerecord is semantically versioned, use:
    add_runtime_dependency 'activerecord', '~> 4.2', '>= 4.2.0'
WARNING:  open-ended dependency on activemodel (>= 4.2.0) is not recommended
  if activemodel is semantically versioned, use:
    add_runtime_dependency 'activemodel', '~> 4.2', '>= 4.2.0'
```

So we seem to trade a little bit of convenience for a lot of potential hassle.

**Pull request merged**
